name: Golang Test Code
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  check_golang_code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Lint
        uses: golangci/golangci-lint-action@v6.1.0
